Student card
GVabal/it-academy-manager-fe pull request #18
Opened 2021-03-20 20:35 UTC by dziugas306

2021-03-21 11:34 UTC, GVabal commented on src/app/admin-page/admin-page.component.html
> +      <app-student-list [isInAdminOrManger] = "true"></app-student-list>
typo in Manager

2021-03-22 07:00 UTC, drachno approved these changes

2021-03-22 07:52 UTC, pauliusnet requested changes
Some changes needed to proceed but all in all - very good work!! 💯

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/manager-page.component.html
> +            <app-student-list [isInAdminOrManger] = "false"></app-student-list>
```suggestion
            <app-student-list [isInAdminOrManager] = "false"></app-student-list>
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.html
> +    <div class="">
```suggestion
    <div>
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.html
> +    <img class="m-4"src="{{student.pictureUrl}}" style="border-radius:50%;" width="300" height="300">
maybe move this styling to ```student-card.component.scss```?
```suggestion
    <img class="m-4"src="{{student.pictureUrl}}">
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.ts
> +  student!: Student;
```suggestion
  student$!: Observable<Student>;
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.ts
> +    }});
```suggestion
    this.student$ = this.store.pipe(
      select(getSelectedStudentId),
      switchMap(studentId => (this.store.select(getStudentById(studentId)) as Observable<Student>))
```

I think you can you use observable straight away :)

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.html
> +<div *ngIf="this.student" class="mt-5 shadow bg-white rounded">
```suggestion
<div *ngIf="this.student$ | async as student" class="mt-5 shadow bg-white rounded">
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/manager-page/student-card/student-card.component.ts
> +}
what about moving this logic to selector and writing a new selector, that would return averageReviewValues :)

2021-03-22 07:52 UTC, pauliusnet commented on src/app/service/review.service.ts
> +    return this.http.get<Review[]>(apiUrl + '/' + id + '/reviews');
```suggestion
    return this.http.get<Review[]>(apiUrl + `/${id}/reviews`);
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/shared-components/radar-chart/radar-chart.component.ts
> +}
```suggestion
}
```
you can remove this ant the ```implements OnInit```, if it is not used :)

2021-03-22 07:52 UTC, pauliusnet commented on src/app/shared-components/student-list/student-list.component.ts
> +  @Input() isInAdminOrManger: boolean | undefined;
```suggestion
  @Input() isManagerView: boolean | undefined;
```
Naming is a bit unclear, so if it's true, does it make admin or manager? Try renaming to this :)

2021-03-22 07:52 UTC, pauliusnet commented on src/app/store/review/review.selectors.ts
> +export const getReviewData =  createSelector(selectReviews, (reviews) =>  mapToReviewData(reviews));
```suggestion
export const getReviewData =  createSelector(selectReviews, (reviews) =>  mapToReviewData(reviews));

export const getReviewDataAverages = createSelector(getReviewData, (data) => ([average(data.overallGrade), average(data.abilityToLearnGrade), average(data.motivationGrade),
         average(data.extraMileGrade), average(data.communicationGrade)]);
         
 function average(list: number[]): number{
    let sum = 0;
    for (const item of list ){
      sum += item;
    }
    const avg = sum / list.length;
    return Number(avg.toFixed(2));
  }
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/store/students/students.reducer.ts
> +  selectedStudentId: number;
```suggestion
  selectedStudentId?: number;
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/store/students/students.reducer.ts
> +  selectedStudentId: -1,
```suggestion
```

2021-03-22 07:52 UTC, pauliusnet commented on src/app/store/students/students.reducer.ts
> +      error: null,
```suggestion
```

2021-03-22 13:58 UTC, GVabal approved these changes

2021-03-22 13:58 UTC, merged